name: 1

on:
  push:
    branches:
      - Dev-Android
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Install
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            .buildozer/android/platform/build-armeabi-v7a_arm64-v8a
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.0
        with:
          path: .buildozer/