name: Build Android

on:
  push:
    branches:
      - Dev-Android
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Buildozer
        uses: actions/cache@v4
        id: cache-buildozer
        with:
          path: |
            ~/.buildozer
            ~/.android
            ~/.android-sdk
            ~/.gradle
          key: ${{ runner.os }}-buildozer
          restore-keys: |
            ${{ runner.os }}-buildozer
      
      - name: Cache Python
        uses: actions/cache@v4
        id: cache-python
        with:
          path: |
            venv
            ~/.cache/pip
          key: ${{ runner.os }}-python
          restore-keys: |
            ${{ runner.os }}-python

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential liblzma-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev \
            openssl libgdbm-dev libgdbm-compat-dev libreadline-dev libffi-dev uuid-dev \
            zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libssl-dev

      - name: Set Up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.8'

      - name: Setup Build Environment
        run: |
          pip3 install --upgrade pip
          pip3 install --user virtualenv
          export PATH="$PATH:$HOME/.local/bin"

      - name: Build Android
        run: |
          if [ ! -d "venv" ]; then
            python3 -m virtualenv venv
          fi
          source venv/bin/activate
          
          pip3 install -q Cython==0.29.33 buildozer wheel setuptools
          
          buildozer android debug --cache-dir ~/.buildozer_cache
          
          find .buildozer -name '*.o' -delete

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.0
        with:
          path: .buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/PhigrosPlayer/build/outputs/apk/debug/PhigrosPlayer-debug.apk