name: Build Kivy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Update dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user --upgrade virtualenv
          export PATH=$PATH:~/.local/bin/
      - name: Build
        run: |
          python3 -m virtualenv venv
          source venv/bin/activate
          pip3 install Cython==0.29.33
          pip3 install buildozer
          buildozer init
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.0
        with:
          path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/build/outputs/apk